INSERT INTO exercises (id, name, description, muscle_group, equipment, difficulty) VALUES 
('52907d76-ab43-49a5-9f3f-4815f9f8fa78','Bench Press', 'The bench press is an upper-body weight training exercise in which the trainee presses a weight upwards while lying on a weight training bench.', 'Chest', ARRAY['Barbell'], 3);
INSERT INTO exercises (name, description, muscle_group, equipment, difficulty) VALUES
('Squat', 'The squat is a lower body exercise that involves the quadriceps, hamstrings, gluteus maximus, hip flexors, and calves.', 'Legs', ARRAY['Barbell'], 3),
('Deadlift', 'The deadlift is a weight training exercise in which a loaded barbell or bar is lifted off the ground to the level of the hips, then lowered to the ground.', 'Back', ARRAY['Barbell'], 3),
('Pull-up', 'A pull-up is an upper-body strength exercise. The pull-up is performed with a palms facing forward grip.', 'Back', ARRAY['Pull-up bar'], 3),
('Push-up', 'A push-up is a common calisthenics exercise beginning from the prone position.', 'Chest', ARRAY[]::text[], 1),
('Plank', 'The plank is an isometric core strength exercise that involves maintaining a position similar to a push-up for the maximum possible time.', 'Core', ARRAY[]::text[], 1),
('Russian Twist', 'The Russian twist is a type of exercise that is used to work the abdominal muscles by performing a twisting motion on the abdomen.', 'Core', ARRAY[]::text[], 2),
('Leg Raise', 'The leg raise is a strength training exercise which targets the iliopsoas (the anterior hip flexors).', 'Core', ARRAY[]::text[], 2),
('Lunge', 'The lunge is a bodyweight exercise that works the muscles in your hips, glutes, quads, hamstrings, and core.', 'Legs', ARRAY[]::text[], 2),
('Dumbbell Curl', 'The dumbbell curl is a weight training exercise performed by flexing the arm at the elbow, then extending the arm while holding a dumbbell.', 'Arms', ARRAY['Dumbbell'], 2),
('Tricep Dip', 'The tricep dip is a bodyweight exercise that targets the triceps.', 'Arms', ARRAY[]::text[], 2),
('Shoulder Press', 'The shoulder press is a weight training exercise that targets the deltoid muscles.', 'Shoulders', ARRAY['Barbell'], 2),
('Bicep Curl', 'The bicep curl is a weight training exercise that targets the biceps.', 'Arms', ARRAY['Barbell'], 2),
('Lat Pulldown', 'The lat pulldown is a strength training exercise that works the upper back.', 'Back', ARRAY['Cable machine'], 2),
('Leg Press', 'The leg press is a weight training exercise in which the individual pushes a weight or resistance away from them using their legs.', 'Legs', ARRAY['Leg press machine'], 2),
('Chest Fly', 'The chest fly is a strength training exercise that works the pectoral muscles.', 'Chest', ARRAY['Cable machine'], 2),
('Hammer Curl', 'The hammer curl is a weight training exercise that targets the biceps and brachialis.', 'Arms', ARRAY['Dumbbell'], 2),
('Skullcrusher', 'The skullcrusher is a strength training exercise that targets the triceps.', 'Arms', ARRAY['Barbell'], 2),
('Calf Raise', 'The calf raise is a strength training exercise that targets the calf muscles.', 'Legs', ARRAY[]::text[], 2),
('Leg Curl', 'The leg curl is a strength training exercise that targets the hamstrings.', 'Legs', ARRAY['Leg curl machine'], 2),
('Leg Extension', 'The leg extension is a strength training exercise that targets the quadriceps.', 'Legs', ARRAY['Leg extension machine'], 2),
('Chest Press', 'The chest press is a strength training exercise that targets the pectoral muscles.', 'Chest', ARRAY['Chest press machine'], 2),
('Shoulder Fly', 'The shoulder fly is a strength training exercise that targets the deltoid muscles.', 'Shoulders', ARRAY['Cable machine'], 2),
('Tricep Extension', 'The tricep extension is a strength training exercise that targets the triceps.', 'Arms', ARRAY['Cable machine'], 2),
('Leg Raise', 'The leg raise is a strength training exercise which targets the iliopsoas (the anterior hip flexors).', 'Core', ARRAY[]::text[], 2),
('Plank', 'The plank is an isometric core strength exercise that involves maintaining a position similar to a push-up for the maximum possible time.', 'Core', ARRAY[]::text[], 1),
('Russian Twist', 'The Russian twist is a type of exercise that is used to work the abdominal muscles by performing a twisting motion on the abdomen.', 'Core', ARRAY[]::text[], 2),
('Leg Curl', 'The leg curl is a strength training exercise that targets the hamstrings.', 'Legs', ARRAY['Leg curl machine'], 2),
('Leg Extension', 'The leg extension is a strength training exercise that targets the quadriceps.', 'Legs', ARRAY['Leg extension machine'], 2),
('Chest Press', 'The chest press is a strength training exercise that targets the pectoral muscles.', 'Chest', ARRAY['Chest press machine'], 2),
('Shoulder Fly', 'The shoulder fly is a strength training exercise that targets the deltoid muscles.', 'Shoulders', ARRAY['Cable machine'], 2),
('Tricep Extension', 'The tricep extension is a strength training exercise that targets the triceps.', 'Arms', ARRAY['Cable machine'], 2),
('Leg Raise', 'The leg raise is a strength training exercise which targets the iliopsoas (the anterior hip flexors).', 'Core', ARRAY[]::text[], 2),
('Plank', 'The plank is an isometric core strength exercise that involves maintaining a position similar to a push-up for the maximum possible time.', 'Core', ARRAY[]::text[], 1),
('Russian Twist', 'The Russian twist is a type of exercise that is used to work the abdominal muscles by performing a twisting motion on the abdomen.', 'Core', ARRAY[]::text[], 2),
('Leg Curl', 'The leg curl is a strength training exercise that targets the hamstrings.', 'Legs', ARRAY['Leg curl machine'], 2),
('Leg Extension', 'The leg extension is a strength training exercise that targets the quadriceps.', 'Legs', ARRAY['Leg extension machine'], 2),
('Chest Press', 'The chest press is a strength training exercise that targets the pectoral muscles.', 'Chest', ARRAY['Chest press machine'], 2),
('Shoulder Fly', 'The shoulder fly is a strength training exercise that targets the deltoid muscles.', 'Shoulders', ARRAY['Cable machine'], 2),
('Tricep Extension', 'The tricep extension is a strength training exercise that targets the triceps.', 'Arms', ARRAY['Cable machine'], 2),
('Leg Raise', 'The leg raise is a strength training exercise which targets the iliopsoas (the anterior hip flexors).', 'Core', ARRAY[]::text[], 2)
;