INSERT INTO exercises (id, name, description, muscle_group, equipment, difficulty) VALUES 
('52907d76-ab43-49a5-9f3f-4815f9f8fa78','Bench Press', 'The bench press is an upper-body weight training exercise in which the trainee presses a weight upwards while lying on a weight training bench.', 'Chest', ARRAY['Barbell'], 3);
INSERT INTO exercises (name, description, muscle_group, equipment, difficulty) VALUES
('Push-up', 'A fundamental upper body exercise that targets chest, shoulders, and triceps. Keep your body straight and elbows close to your body.', 'Chest', ARRAY[]::text[], 1),
('Diamond Push-up', 'A variation of the push-up with hands close together forming a diamond shape, emphasizing triceps.', 'Arms', ARRAY[]::text[], 2),
('Decline Push-up', 'Feet elevated push-up that targets upper chest and shoulders more intensely.', 'Chest', ARRAY[]::text[], 2),
('Pseudo Planche Push-up', 'Advanced push-up variation with hands positioned further back, targeting chest and shoulders with increased difficulty.', 'Chest', ARRAY[]::text[], 3),
('Pull-up', 'Basic pull-up with overhand grip, targeting back and biceps. Pull until chin clears the bar.', 'Back', ARRAY['Pull-up bar'], 2),
('Chin-up', 'Pull-up variation with underhand grip, emphasizing biceps more than standard pull-up.', 'Back', ARRAY['Pull-up bar'], 2),
('L-sit Pull-up', 'Pull-up variation with legs held straight out in front, increasing core engagement.', 'Back', ARRAY['Pull-up bar'], 3),
('Muscle-up', 'Advanced movement combining pull-up and dip, transitioning from hanging below to supporting above the bar.', 'Back', ARRAY['Pull-up bar'], 3),
('Hollow Hold', 'Isometric core exercise that builds foundational core strength. Lie on back with legs and arms extended.', 'Core', ARRAY[]::text[], 1),
('L-sit Hold', 'Static hold with legs straight out in front while supporting bodyweight on hands.', 'Core', ARRAY['Parallel bars'], 2),
('Front Lever', 'Advanced static hold where body is held parallel to the ground while hanging from a bar.', 'Back', ARRAY['Pull-up bar'], 3),
('Planche', 'Advanced static hold where body is held parallel to the ground while supporting on hands.', 'Shoulders', ARRAY[]::text[], 3),
('Pistol Squat', 'Single-leg squat requiring balance and strength. Lower body until back leg touches ground.', 'Legs', ARRAY[]::text[], 2),
('Shrimp Squat', 'Single-leg squat variation with back leg held behind body, emphasizing quadriceps.', 'Legs', ARRAY[]::text[], 2),
('Nordic Curl', 'Eccentric hamstring exercise performed with a partner or anchor point.', 'Legs', ARRAY[]::text[], 3),
('Sissy Squat', 'Quad-focused squat variation with knees moving forward and heels elevated.', 'Legs', ARRAY[]::text[], 2),
('Handstand Hold', 'Basic inverted position against a wall, building shoulder strength and balance.', 'Shoulders', ARRAY['Wall'], 2),
('Freestanding Handstand', 'Advanced handstand without wall support, requiring significant balance and strength.', 'Shoulders', ARRAY[]::text[], 3),
('Handstand Push-up', 'Vertical pressing movement performed in handstand position.', 'Shoulders', ARRAY['Wall'], 3),
('Dips', 'Basic dip movement on parallel bars, targeting chest, shoulders, and triceps.', 'Arms', ARRAY['Parallel bars'], 2),
('L-sit Dip', 'Dip variation with legs held straight out in front, increasing core engagement.', 'Arms', ARRAY['Parallel bars'], 3),
('Russian Dip', 'Advanced dip variation with deep range of motion and explosive movement.', 'Arms', ARRAY['Parallel bars'], 3),
('Back Lever', 'Static hold where body is held parallel to the ground while hanging from a bar.', 'Back', ARRAY['Pull-up bar'], 3),
('Human Flag', 'Advanced static hold where body is held horizontally while gripping a vertical pole.', 'Back', ARRAY['Pole'], 3),
('Victorian Cross', 'Advanced static hold with arms spread wide while supporting bodyweight.', 'Back', ARRAY['Parallel bars'], 3);